'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const core = require('./media-pipeline.cjs');
const fixtures = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/media-contracts.json'), 'utf8'));
const audio = fixtures.validAudio;
const sha = audio.sha256;

test('validates bounded audio upload metadata', () => assert.equal(core.validateUpload(audio).kind, 'audio'));
test('accepts supported bounded video', () => assert.equal(core.validateUpload({ ...audio, filename: 'v.mp4', mimeType: 'video/mp4', sizeBytes: 10_000 }).kind, 'video'));
test('rejects path traversal filenames', () => assert.throws(() => core.validateUpload({ ...audio, filename: '../voice.wav' }), { code: 'INVALID_FILENAME' }));
test('rejects dotfiles', () => assert.throws(() => core.validateUpload({ ...audio, filename: '.env' }), { code: 'INVALID_FILENAME' }));
test('rejects unsupported media types', () => assert.throws(() => core.validateUpload({ ...audio, mimeType: 'application/zip' }), { code: 'UNSUPPORTED_FORMAT' }));
test('rejects oversized uploads before bytes are accepted', () => assert.throws(() => core.validateUpload({ ...audio, sizeBytes: 257 * 1024 ** 2 }), { code: 'SIZE_LIMIT' }));
test('requires a full SHA-256 checksum', () => assert.throws(() => core.validateUpload({ ...audio, sha256: 'short' }), { code: 'CHECKSUM_REQUIRED' }));
test('creates tenant-separated content-addressed object keys', () => assert.notEqual(core.objectKey('one', core.validateUpload(audio), 'id'), core.objectKey('two', core.validateUpload(audio), 'id')));
test('accepts a matching bounded media probe', () => assert.equal(core.validateProbe(core.validateUpload(audio), { mimeType: 'audio/wav', codec: 'pcm_s16le', durationMs: 1000, sampleRate: 48000, channels: 1 }).sampleRate, 48000));
test('rejects MIME mismatch after object upload', () => assert.throws(() => core.validateProbe(core.validateUpload(audio), { mimeType: 'audio/mpeg', codec: 'mp3', durationMs: 1, sampleRate: 48000, channels: 1 }), { code: 'MIME_MISMATCH' }));
test('rejects adversarial codec metadata', () => assert.throws(() => core.validateProbe(core.validateUpload(audio), { mimeType: 'audio/wav', codec: 'shell', durationMs: 1, sampleRate: 48000, channels: 1 }), { code: 'CODEC_NOT_ALLOWED' }));
test('rejects the adversarial probe fixture', () => assert.throws(() => core.validateProbe(core.validateUpload(audio), fixtures.adversarialProbe), { code: 'CODEC_NOT_ALLOWED' }));
test('rejects overlong media', () => assert.throws(() => core.validateProbe(core.validateUpload(audio), { mimeType: 'audio/wav', codec: 'pcm_s16le', durationMs: 14_400_001, sampleRate: 48000, channels: 1 }), { code: 'DURATION_LIMIT' }));
test('rejects invalid audio sample rates', () => assert.throws(() => core.validateProbe(core.validateUpload(audio), { mimeType: 'audio/wav', codec: 'pcm_s16le', durationMs: 1, sampleRate: 1, channels: 1 }), { code: 'INVALID_SAMPLE_RATE' }));
test('validates video dimensions and frame rate', () => assert.equal(core.validateProbe(core.validateUpload({ ...audio, filename: 'v.mp4', mimeType: 'video/mp4' }), { mimeType: 'video/mp4', codec: 'h264', durationMs: 100, width: 1920, height: 1080, fps: 30 }).width, 1920));
test('accepts the bounded video fixture and its probe', () => assert.equal(core.validateProbe(core.validateUpload(fixtures.validVideo), fixtures.validVideoProbe).codec, 'h264'));
test('job state rejects skipped success', () => assert.throws(() => core.transitionJob({ status: 'QUEUED' }, 'SUCCEEDED', {}), { code: 'INVALID_JOB_TRANSITION' }));
test('job success requires provider receipt and output', () => assert.throws(() => core.transitionJob({ status: 'PROVIDER_PENDING' }, 'SUCCEEDED', {}), { code: 'RECEIPT_REQUIRED' }));
test('provider-pending cancellation requires confirmation', () => assert.throws(() => core.transitionJob({ status: 'PROVIDER_PENDING' }, 'CANCELLED', {}), { code: 'PROVIDER_CANCELLATION_REQUIRED' }));
test('provider selection respects capability, quota, and priority', () => { const picked = core.chooseProvider([{ id: 'slow', status: 'ACTIVE', capabilities: ['TRANSCODE'], maxInputBytes: 100, usageDate: '2026-01-01', usedToday: 0, dailyQuota: 1, priority: 2, costWeight: 1 }, { id: 'fast', status: 'ACTIVE', capabilities: ['TRANSCODE'], maxInputBytes: 100, usageDate: '2026-01-01', usedToday: 0, dailyQuota: 1, priority: 1, costWeight: 1 }], { jobType: 'TRANSCODE', inputBytes: 10, providersTried: [] }, new Date('2026-01-01')); assert.equal(picked.id, 'fast'); });
test('provider selection excludes already tried providers for failover', () => { const picked = core.chooseProvider([{ id: 'one', status: 'ACTIVE', capabilities: ['EXPORT'], maxInputBytes: 100, usageDate: 'x', usedToday: 0, dailyQuota: 1, priority: 1, costWeight: 1 }, { id: 'two', status: 'ACTIVE', capabilities: ['EXPORT'], maxInputBytes: 100, usageDate: 'x', usedToday: 0, dailyQuota: 1, priority: 2, costWeight: 1 }], { jobType: 'EXPORT', inputBytes: 1, providersTried: ['one'] }); assert.equal(picked.id, 'two'); });
test('provider selection fails explicitly without capacity', () => assert.throws(() => core.chooseProvider([], { jobType: 'EXPORT', inputBytes: 1 }), { code: 'NO_PROVIDER_CAPACITY' }));
test('classifies timeouts and 429 as retryable failover', () => { assert.equal(core.classifyProviderFailure({ status: 429, message: 'quota' }).failover, true); assert.equal(core.classifyProviderFailure({ message: 'timeout' }).retryable, true); });
const timeline = { tracks: [{ type: 'audio', clips: [{ id: 'c1', assetId: 'a1', startMs: 0, sourceStartMs: 0, durationMs: 1000 }] }] };
test('validates timeline and produces checksum', () => assert.match(core.validateTimeline(timeline, { a1: 1000 }).checksum, /^[a-f0-9]{64}$/));
test('rejects overlapping clips', () => assert.throws(() => core.validateTimeline({ tracks: [{ type: 'audio', clips: [...timeline.tracks[0].clips, { id: 'c2', assetId: 'a1', startMs: 500, sourceStartMs: 0, durationMs: 100 }] }] }, { a1: 1000 }), { code: 'CLIP_OVERLAP' }));
test('rejects clips beyond source duration', () => assert.throws(() => core.validateTimeline(timeline, { a1: 999 }), { code: 'CLIP_OUT_OF_RANGE' }));
test('timeline versions are immutable and sequential', () => assert.equal(core.nextTimelineVersion({ version: 3, checksum: 'different' }, timeline, { a1: 1000 }).version, 4));
test('timeline rejects no-op versions', () => { const current = core.nextTimelineVersion(null, timeline, { a1: 1000 }); assert.throws(() => core.nextTimelineVersion(current, timeline, { a1: 1000 }), { code: 'NO_TIMELINE_CHANGE' }); });
test('rejects more than 64 timeline tracks before processing clips', () => assert.throws(() => core.validateTimeline({ tracks: Array.from({ length: 65 }, () => ({ type: 'audio', clips: [] })) }), { code: 'INVALID_TIMELINE' }));
test('rejects more than 10000 clips on one track before traversal', () => assert.throws(() => core.validateTimeline({ tracks: [{ type: 'audio', clips: Array(10_001).fill({}) }] }), { code: 'INVALID_TRACK' }));
test('preview rejection requires reviewer comment', () => assert.throws(() => core.decidePreview({ status: 'PENDING' }, { decision: 'REJECTED', reviewedBy: 'u' }), { code: 'COMMENT_REQUIRED' }));
test('preview approval decisions are immutable', () => assert.throws(() => core.decidePreview({ status: 'APPROVED' }, { decision: 'REJECTED', reviewedBy: 'u', comment: 'x' }), { code: 'APPROVAL_ALREADY_DECIDED' }));
const captions = { language: 'en-US', cues: [{ startMs: 0, endMs: 1000, text: 'Hello' }, { startMs: 1000, endMs: 2000, text: 'world' }] };
test('validates caption language, bounds, and cue ordering', () => assert.equal(core.validateCaptions(captions).cues.length, 2));
test('rejects overlapping caption cues', () => assert.throws(() => core.validateCaptions({ ...captions, cues: [{ startMs: 0, endMs: 1000, text: 'a' }, { startMs: 900, endMs: 1100, text: 'b' }] }), { code: 'INVALID_CUE_TIME' }));
test('rejects more than 20000 caption cues before rendering', () => assert.throws(() => core.validateCaptions({ language: 'en', cues: Array(20_001).fill({}) }), { code: 'INVALID_CAPTIONS' }));
test('renders valid WebVTT timestamps', () => assert.match(core.toWebVtt(captions), /00:00:01\.000 --> 00:00:02\.000/));
test('export requires preview approval', () => assert.throws(() => core.createExport({ previewApproval: { status: 'PENDING' }, preset: { format: 'mp3' } }), { code: 'PREVIEW_APPROVAL_REQUIRED' }));
test('accessible export requires captions', () => assert.throws(() => core.createExport({ previewApproval: { id: 'p', status: 'APPROVED' }, preset: { format: 'mp4-h264', accessible: true }, timelineVersionId: 'v' }), { code: 'CAPTIONS_REQUIRED' }));
test('accessible manifest exposes controls, captions, and provenance', () => { const manifest = core.accessiblePlaybackManifest({ asset: { state: 'READY', objectUri: 'https://objects.test/a', mimeType: 'audio/wav', durationMs: 1000, provenance: { sha256: sha } }, captions: [{ validated: true, objectUri: 'https://objects.test/c', language: 'en', isDefault: true }] }); assert.equal(manifest.keyboardAccessible, true); assert.equal(manifest.captions.length, 1); });
test('durable queue is tenant-idempotent', () => { const q = new core.DurableQueueModel({ id: () => 'j' }); const a = q.enqueue({ businessId: 'b', idempotencyKey: 'k' }); const b = q.enqueue({ businessId: 'b', idempotencyKey: 'k' }); assert.equal(a.id, b.id); });
test('durable queue enforces leases and failure backoff', () => { let now = 0; const q = new core.DurableQueueModel({ now: () => now, id: () => 'j' }); q.enqueue({ businessId: 'b', idempotencyKey: 'k', maxAttempts: 2 }); q.claim('w'); assert.throws(() => q.fail('j', 'other', { message: 'timeout' }), { code: 'LEASE_CONFLICT' }); assert.equal(q.fail('j', 'w', { message: 'timeout' }).status, 'RETRY_WAIT'); now = 6000; q.claim('w'); assert.equal(q.fail('j', 'w', { message: 'timeout' }).status, 'DEAD_LETTER'); });
test('durable queue completion requires real receipt', () => { const q = new core.DurableQueueModel({ id: () => 'j' }); q.enqueue({ businessId: 'b', idempotencyKey: 'k' }); q.claim('w'); assert.throws(() => q.complete('j', 'w', {}), { code: 'RECEIPT_REQUIRED' }); });
test('durable queue cancellation is tenant-scoped', () => { const q = new core.DurableQueueModel({ id: () => 'j' }); q.enqueue({ businessId: 'b', idempotencyKey: 'k' }); assert.throws(() => q.cancel('other', 'j'), { code: 'NOT_FOUND' }); assert.equal(q.cancel('b', 'j').status, 'CANCELLED'); });
